# environment setup
language: swift
osx_image: xcode11.4

cache:
  bundler: true

before_install:
  - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"

  # install dependencies
install:
  - bundle install
  - bundle exec pod install

# jobs and stages to run
jobs:
  include:
    - stage: "Test"
      name: "Unit tests"
      script:
        - bundle exec fastlane tests_mock

