# environment setup
language: swift
osx_image: xcode11.4

cache:
    bundler: true
    cocoapods: true

before_install:
    # Make sure we use the bundler version that is provided in the Gemfile.lock file
  - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"

  # install dependencies
install:
  - bundle install
  - bundle exec pod install

# jobs and stages to run
jobs:
  include:
    # Tests
    - stage: "test"
      name: "Unit tests"
      script:
        - bundle exec fastlane tests_mock
    # Docs deployment
    - stage: "deploy/docs"
      name: "Deploy App Documentation to GitHub Pages"
      script:
        - "jazzy --clean --no-objc --author David Bielik --author_url https://dvdblk.com --github_url https://github.com/uzh-footm/iOS --output docs --xcodebuild-arguments -m Betterpick --theme fullwidth"
      deploy:
        provider:     pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir:    docs
      on:
        branch: develop
