# environment setup
language: swift
os: osx
osx_image: xcode11.4

cache:
    bundler: true
    cocoapods: true
    directories:
      - "./vendor/bundle"

before_install:
  - git config --global user.name "travis-ci"
  - git config --global user.email travisci.bp@dvdblk.com
  - git remote set-url origin https://uzh-footm:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}

  # install dependencies
install:
  - bundle config set path 'vendor/bundle'
  - bundle install
  - bundle exec pod install

stages:
  - name: Info
  # Test stage
  # Allow only if the type is a pull request and the branch is 'feature/...'
  - name: Test
    if: type = pull_request AND branch IN (develop, master)
  # Deploy new release stage
  # Allow only if the type is a PR and the branch is 'release/...'
  - name: Release
    if: type = pull_request AND branch = master
  # Deploy docs stage
  # Allow only if we push to master
  # TODO: Add check for: commit_message =~ ^[Release].*$
  - name: Deploy Documentation
    if: type = push AND branch = master



# jobs and stages to run
jobs:
  include:
    - stage: Info
      name: "Just a test"
      script:
        - touch tempfile123
        - git add tempfile123
        - git commit -m "travis test commit"
        - git push origin --tags

    ###################### master ######################
    ### Docs deployment
    - stage: Deploy Documentation
      name: "Deploy iOS App Documentation from master to GitHub Pages"
      deploy:
        provider:     pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir:    docs/src
    - script:
        - 

    ### Tests
    - stage: Test
      name: "UI & Unit tests"
      script:
        - bundle exec fastlane tests_mocks
      after_failure:
        - cat /Users/travis/Library/Developer/Xcode/DerivedData/Betterpick-cswmbpqoqkjrbsetljjetwhmkdcr/Build/Intermediates.noindex/Betterpick.build/Debug-iphonesimulator/Betterpick.build/Script-8908844F24449EA40080CCBF.sh

    ### New Release Deployment
    - stage: Release
      ## Screenshots
      script:
        - bundle exec fastlane deploy_screenshots
      name: "Generate Screenshots"
      ## Documentation generation
    - script:
        - bundle exec fastlane generate_and_commit_documentation
      name: "Generate Documentation"
      ## TF Upload
    - script:
        - bundle exec fastlane deploy_beta_mocks
      name: "TestFlight Upload"
      