# environment setup
language: swift
osx_image: xcode11.4

cache:
    bundler: true
    directories:
      
    cocoapods: true

before_install:
    # Make sure we use the bundler version that is provided in the Gemfile.lock file
  - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"

  # install dependencies
install:
  - bundle config set path 'vendor/bundle'
  - bundle install
  - bundle info jazzy
  - bundle exec pod install

stages:
  - test
  - deploy/docs

# jobs and stages to run
jobs:
  include:
    # Tests
    - stage: test
      name: "iOS App unit tests"
      script:
        - bundle exec fastlane tests_mock
      if: type = pull_request
    # Docs deployment
    - stage: deploy/docs
      name: "Deploy iOS App Documentation to GitHub Pages"
      script:
        - bundle exec fastlane generate_docs
      after_failure:
        - find /var/folders/z3 -name '*.log' -exec tail -200 {} \;
      deploy:
        provider:     pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir:    docs/src
      on:
        branch: develop
