# environment setup
language: ruby
os: osx
osx_image: xcode11.3

cache:
    bundler: true
    cocoapods: true

before_install:
  - gem install jazzy

stages:
  - test
  - deploy/docs

# jobs and stages to run
jobs:
  include:
    # Tests
    - stage: test
      name: "iOS App unit tests"
      script:
        - bundle exec fastlane tests_mock
      if: type = pull_request
    # Docs deployment
    - stage: deploy/docs
      name: "Deploy iOS App Documentation to GitHub Pages"
      script:
        #- bundle exec fastlane generate_docs
        - jazzy --config docs/.jazzy.yaml
      after_failure:
        - find /var/folders/z3 -name '*.log' -exec tail -800 {} \;
      deploy:
        provider:     pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir:    docs/src
      on:
        branch: develop
