# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs tests for the target that uses BetterpickAPIManagerMock"
  lane :tests_mocks do
    run_tests(
      scheme: "Betterpick Mock",
      devices: ["iPhone 11 Pro"],
    )
  end

  desc "Runs tests"
  lane :tests do
    run_tests(scheme: "Betterpick")
  end

  desc "Documentation generation via Jazzy"
  lane :generate_docs do
    jazzy(config: "docs/.jazzy.yaml")
  end

  desc "Testflight mocks"
  lane :testflight_mocks do
    sync_code_signing(type: "appstore")
    build_app(
      scheme: "Betterpick Mock",
      output_directory: "build/",
      build_path: "build/"
    )
    upload_to_testflight
  end
end
