# A list of devices you want to take the screenshots from
devices([
  "iPhone SE (2nd generation)",
  "iPhone 11",
  "iPhone 11 Pro",
  "iPhone 11 Pro Max"
])

# The name of the scheme which contains the UI Tests
scheme("BetterpickScreenshots")

# Where should the resulting screenshots be stored?
output_directory("./assets/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception.
override_status_bar(true)

# Prevent error 65:
# https://github.com/fastlane/fastlane/issues/14201
concurrent_simulators(false)