#module: Betterpick
author: David Bielik
title: Betterpick iOS Documentation
author_url: https://dvdblk.com
github_url: https://github.com/uzh-footm/iOS
hide_documentation_coverage: true
#documentation: Extra/*.md
#abstract: Sections/*.md
#docset_playground_url: https://repl.it/F9J7/1
output: src
xcodebuild_arguments: 
    - -scheme 
    - Betterpick
    - -workspace 
    - Betterpick.xcworkspace
min_acl: private